# print(type("Hello world"))
# print(type(1))
# print(type(1.0))

# var1 = input("Give me a number: ")
# print(type(var1))
# var1 = int(var1)
# print(type(var1))
# var1 = float(var1)
# print(type(var1))

var1 = float(input("Give me a number: "))
print(type(var1))
print(var1)
print("My number is",str(var1))