# Ask the user for the first number and save it as a variable (3 points)
first_number = input("Give me a number: ")
# Ask the user for the second number and save it as a variable (3 points)
second_number = input("Give me a second number: ")
# Save the sum of the numbers as a variable (3 points)
sum_of_first_and_second_number = int(first_number) + int(second_number)
# Save the difference of the numbers as a variable (3 points)
difference_of_first_and_second_number = int(first_number) - int(second_number)
# Save the product of the numbers as a variable (3 points)
product_of_first_and_second_number = int(first_number) * int(second_number)
# Save the quotient of the numbers as the fourth output (note that if the second number is a zero, this will crash the program. This is fine for now, we will learn how to deal with this later) (3 points)
quotient_of_first_and_second_number = int(first_number) / int(second_number)
# Output the sum, difference, product and quotient of the two numbers on one line. (2 points)
print("Sum:",sum_of_first_and_second_number)
print("Difference:",difference_of_first_and_second_number)
print("Product:",product_of_first_and_second_number)
print("Quotient:",quotient_of_first_and_second_number)
